dist:     focal
language: c

os:
  - linux
    #  - osx
    #  - freebsd

arch:
  - amd64
  - arm64
  - s390x
  - ppc64le

compiler:
  - gcc
  - clang

#matrix:
#  exclude:
#    - os: osx
#      compiler: gcc

addons:
  apt:
    packages:
      - autoconf
      - automake

before_script:
  - sudo apt-get update -q
  - sudo apt-get install --only-upgrade autoconf
  - export AUTOCONF_VERSION=2.71

script:
  - arch
  - cd src
  - autoconf --version
  - ./autogen.sh
  - ./configure CFLAGS='-Wall'
  - make
  - ./screen -v
  - ./screen -h
  - ./screen -S -d -m bash -c 'ping -c 8 localhost'; true
  - ./screen -ls; true
  - ./screen -S shortname -d -m bash -c 'ping -c 8 localhost'
  - ./screen -ls
  - ./screen -S shortname -X sessionname; true
  - make clean
  - ./configure CFLAGS='-Wall -DDEBUG'
  - make
  - ./screen -v
  - ./screen -h
  - ./screen -S -d -m bash -c 'ping -c 8 localhost'; true
  - ./screen -ls; true
  - ./screen -S shortname -d -m bash -c 'ping -c 8 localhost'
  - ./screen -ls
  - ./screen -S shortname -X sessionname; true
  - ./screen -ls; true
  - ./screen -S shortname -X sessionname testtest
  - ./screen -r; true
  - ./screen -S averyverylongsesssionnameaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -d -m bash -c 'ping -c 8 localhost'; true
  - ./screen -ls; true
  - ls -la /tmp/debug/
  - cat /tmp/debug/SCREEN*
  - man ./doc/screen.1
