language:	c
os:			linux
dist:		focal

#arch:
#	- amd64
#	- arm64

compiler:
  - gcc
  - clang

#git:
#  depth: false

script:
  - cd src
  - ./autogen.sh
  - ./configure CFLAGS="-Wall -DDEBUG"
  - make clean
  - make
  - ./screen -v
  - ./screen -h
  - make clean
