name: C_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: autogen
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: ./autogen.sh

    - name: configure
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: ./configure

    - name: make
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: make

    - name: make clean
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: make clean

  openbsd:
    runs-on: macos-12
    steps:
    - name: Bootstrap OpenBSD-latest
      uses: mario-campos/emulate@v1
      with:
        operating-system: openbsd-latest

    - name: Install Dependencies
      run: pkg_add gmake git automake-1.16.5

    - name: Build
      run: |
        git clone https://github.com/alexander-naumov/screen.git
        cd screen/src
        export AUTOCONF_VERSION=2.69
        export AUTOMAKE_VERSION=1.16
        ./autogen.sh
        ./configure --disable-pam
        gmake

    - test:
      run: |
        ./screen -v
        ./screen -help

  macos:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: autogen
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: ./autogen.sh

    - name: configure
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: ./configure

    - name: make
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: make

    - name: make clean
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: make clean
