name: C_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-20.04 ]
        arch: [armv6l, armv7l, aarch64]
        include:
        - arch: armv6l
          cpu: arm1176
          base_image: raspios_lite:latest
          cpu_info: raspberrypi_zero_w
        - arch: armv7l
          cpu: cortex-a7
          base_image: raspios_lite:latest
          cpu_info: raspberrypi_3b
        - arch: aarch64
          cpu: cortex-a53
          base_image: raspios_lite_arm64:latest
          cpu_info: raspberrypi_zero2_w_arm64_w
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: autogen
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: ./autogen.sh

    - name: configure
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: ./configure

    - name: make
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: make

    - name: make clean
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: make clean


  openbsd:
    runs-on: macos-12
    steps:
    - name: Bootstrap OpenBSD-latest
      uses: mario-campos/emulate@v1
      with:
        operating-system: openbsd-latest

    - name: Install Dependencies
      run: pkg_add gmake git automake-1.15.1

    - name: Build and Test
      run: |
        git clone https://github.com/alexander-naumov/screen.git
        cd screen/src
        export AUTOCONF_VERSION=2.69
        export AUTOMAKE_VERSION=1.15
        ./autogen.sh
        ./configure --disable-pam
        gmake
        ./screen -v
        ./screen -help


  macos:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: autogen
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: ./autogen.sh

    - name: configure
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: ./configure

    - name: make
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: make

    - name: make clean
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: make clean
