name: FreeBSD

on:
  push:
    branches: [ "main", "freebsd" ]
  pull_request:
    branches: [ "main", "freebsd" ]

jobs:
  freebsd:
    runs-on: macos-12
    steps:
    - name: Bootstrap FreeBSD-latest
      uses: mario-campos/emulate@v1
      with:
        operating-system: freebsd-latest

    - name: Install Dependencies
      run: pkg install -y gmake print/texinfo git autoconf indexinfo automake

    - name: Build
      run: |
        uname -a
        git clone https://github.com/alexander-naumov/screen.git
        cd screen/src
        #export AUTOCONF_VERSION=2.69
        #export AUTOMAKE_VERSION=1.15
        echo "> ./autogen.sh"
        ./autogen.sh
        echo "> clang -v"
        clang -v
        echo "> cc=clang ./configure --disable-pam CFLAGS='-Wall'"
        cc=clang ./configure --disable-pam CFLAGS='-Wall'
        echo "> gmake"
        gmake

    - name: DEBUG build
      run: |
        echo "> cc=clang ./configure --disable-pam CFLAGS='-Wall -DDEBUG'"
        cc=clang ./configure --disable-pam CFLAGS='-Wall -DDEBUG'
        echo "> gmake"
        gmake

    - name: Test
      run: |
        cd screen/src
        echo "> pwd"
        pwd
        echo "> screen -v"
        ./screen -v
        echo "> screen --help"
        ./screen -help
