name: macOS

on:
  push:
    branches: [ main, macos ]
  pull_request:
    branches: [ main, macos ]

env:
  CC: clang

jobs:
  macos:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - using: 'node16'

    - name: Install dependency
      working-directory: ${{github.workspace}}/src
      run: brew install automake make gcc ncurses libevent

    - name: Create Build Environment
      working-directory: ${{github.workspace}}/src
      run: ./autogen.sh

    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: |
        uname -a
        clang -v
        cc=clang ./configure --disable-pam CFLAGS='-Wall'
        # -DDEBUG -Wno-implicit-function-declaration"

    - name: Build
      working-directory: ${{github.workspace}}/src
      shell: bash
      run: make

    - name: Test
      working-directory: ${{github.workspace}}/src
      shell: bash
      run: |
        echo "> pwd"
        pwd
        echo "> screen -v"
        ./screen -v
        echo "> screen --help"
        ./screen -help

