name: NetBSD

on:
  push:
    branches: [ "main", "netbsd" ]
  pull_request:
    branches: [ "main", "netbsd" ]

jobs:
  netbsd:
    runs-on: macos-12
    steps:
    - name: Bootstrap NetBSD-latest
      uses: actions/checkout@v4
      #uses: mario-campos/emulate@v1
      with:
        operating-system: netbsd-latest

    - name: Build
      run: |
        uname -a
        git clone https://github.com/alexander-naumov/screen.git
        cd screen/src
        export AUTOCONF_VERSION=2.71
        export AUTOMAKE_VERSION=1.15
        ./autogen.sh
        echo "> ./configure --disable-pam CFLAGS='-Wall -DDEBUG'"
        ./configure --disable-pam CFLAGS="-Wall -DDEBUG"
        echo "> make"
        make

    - name: Test
      run: |
        cd screen/src
        echo "> pwd"
        pwd
        echo "> screen -v"
        ./screen -v
        echo "> screen --help"
        ./screen -help
