name: OpenBSD aarch64

on: [push]

jobs:
  openbsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: cross-platform-actions/action@v0.21.1
        with:
          operating_system: openbsd
          architecture: arm64
          version: '7.4'
          run: |
            uname -a
            echo $SHELL
            pwd
            ls -lah
            whoami
            env | sort
            sudo pkg_add gmake git automake-1.15.1
            export AUTOCONF_VERSION=2.71
            export AUTOMAKE_VERSION=1.15
            cd src
            ls -lah
            ./autogen.sh
            echo $?
            ./configure --disable-pam CFLAGS="-Wall -DDEBUG"
            gmake

      - name: Test
        run: |
          cd screen/src
          echo "> pwd"
          pwd
          echo "> screen -v"
          ./screen -v
          echo "> screen --help"
          ./screen -help
