name: OpenBSD x86_64

on: [push]

jobs:
  openbsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: cross-platform-actions/action@v0.21.1

        with:
          architecture: x86_64
          operating_system: openbsd
          version: '7.4'
          hypervisor: xhyve
          sync_files: runner-to-vm
          shell: bash
          run: |
            uname -a
            echo $SHELL
            pwd
            ls -lah
            whoami
            env | sort
            sudo pkg_add gmake automake
            export AUTOCONF_VERSION=2.71
            export AUTOMAKE_VERSION=1.15
            cd src
            ls -lah
            ./autogen.sh
            echo $?
            ./configure --disable-pam CFLAGS="-Wall -DDEBUG"
            gmake

      - name: Test
        run: |
          cd screen/src
          echo "> pwd"
          pwd
          echo "> screen -v"
          ./screen -v
          echo "> screen --help"
          ./screen -help
