name: OpenBSD 7.5 aarch64

on: [push]

jobs:
  openbsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cross-platform-actions/action@v0.24.0

        with:
          operating_system: openbsd
          memory: 4G
          architecture: arm64
          version: '7.5'
          sync_files: runner-to-vm
          shell: bash
          run: |
            echo "------------------------------------------------------------"
            echo "> uname -a"
            uname -a

            echo "------------------------------------------------------------"
            echo "> echo $SHELL"
            echo $SHELL

            echo "------------------------------------------------------------"
            echo "> env | sort"
            env | sort

            echo "------------------------------------------------------------"
            echo "> sudo pkg_add gmake automake-1.16.5 autoconf-2.71"
            sudo pkg_add gmake automake-1.16.5 autoconf-2.71

            echo "------------------------------------------------------------"
            echo "> export AUTOCONF_VERSION=2.71"
            export AUTOCONF_VERSION=2.71

            echo "------------------------------------------------------------"
            echo "> export AUTOMAKE_VERSION=1.16"
            export AUTOMAKE_VERSION=1.16

            echo "------------------------------------------------------------"
            echo "> ls -la /usr/local/bin/aclocal-*"
            ls -la /usr/local/bin/aclocal-*

            echo "------------------------------------------------------------"
            echo "> cd src"
            cd src

            echo "------------------------------------------------------------"
            echo "> ls -lah"
            ls -lah

            echo "------------------------------------------------------------"
            echo "> ./autogen.sh"
            ./autogen.sh

            echo "------------------------------------------------------------"
            echo "> echo $?"
            echo $?

            echo "------------------------------------------------------------"
            echo "> ./configure --disable-pam CFLAGS='-Wall'"
            ./configure --disable-pam CFLAGS="-Wall"

            echo "------------------------------------------------------------"
            echo "> gmake"
            gmake

            echo "------------------------------------------------------------"
            echo "> ./screen -v"
            ./screen -v

            echo "------------------------------------------------------------"
            echo "> ./screen -ls || echo $?"
            ./screen -ls || echo $?

            echo "------------------------------------------------------------"
            echo "> ./screen --help"
            ./screen --help
