name: OpenBSD

on: [push]

jobs:
  openbsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: cross-platform-actions/action@v0.21.1
        with:
          operating_system: openbsd
          version: '7.4'
          hypervisor: xhyve
          run: |
            uname -a
            echo $SHELL
            echo "> pkg_add gmake git automake-1.15.1"
            pkg_add gmake git automake-1.15.1
            git clone https://github.com/alexander-naumov/screen.git
            cd screen/src
            export AUTOCONF_VERSION=2.71
            export AUTOMAKE_VERSION=1.15
            ./autogen.sh
            echo "> ./configure --disable-pam CFLAGS='-Wall -DDEBUG'"
            ./configure --disable-pam CFLAGS="-Wall -DDEBUG"
            echo "> gmake"
            gmake

      - name: Test
        run: |
          cd screen/src
          echo "> pwd"
          pwd
          echo "> screen -v"
          ./screen -v
          echo "> screen --help"
          ./screen -help
