name: Solaris 11.4 x86_64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  solaris:
    runs-on: macos-12
    steps:
    - name: Bootstrap Solaris
      uses: actions/checkout@v3

    - name: Install Dependencies
      uses: vmactions/solaris-vm@v0
      with:
        prepare: |
          pkgutil -y -i git automake autoconf gcc #clang
          gcc -v

    - name: Build
      run: |
          uname -a
          cat /etc/release
          git clone https://github.com/alexander-naumov/gnu-screen.git
          cd gnu-screen/src
          ./autogen.sh
          echo "> ./configure --disable-pam CFLAGS='-Wall -DDEBUG'"
          ./configure --disable-pam CFLAGS="-Wall -DDEBUG"
          make
          ./screen -v
          ./screen --help
