name: Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [zero_raspbian, zero_raspios, zero_dietpi, zero2_raspios, zero2_dietpi, zero2_64_raspios, zero2_64_dietpi]
        include:
        - target: zero_raspbian
          cpu: arm1176
          cpu_info: cpuinfo/raspberrypi_zero_w
          base_image: raspbian_lite:latest

        - target: zero_raspios
          cpu: arm1176
          cpu_info: cpuinfo/raspberrypi_zero_w
          base_image: raspios_lite:latest

        - target: zero_dietpi
          cpu: arm1176
          cpu_info: cpuinfo/raspberrypi_zero_w
          base_image: dietpi:rpi_armv6_bullseye

        - target: zero2_raspios
          cpu: cortex-a7
          cpu_info: cpuinfo/raspberrypi_zero2_w
          base_image: raspios_lite:latest

        - target: zero2_dietpi
          cpu: cortex-a7
          cpu_info: cpuinfo/raspberrypi_zero2_w
          base_image: dietpi:rpi_armv7_bullseye

        - target: zero2_64_raspios
          cpu: cortex-a53
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
          base_image: raspios_lite_arm64:latest

        - target: zero2_64_dietpi
          cpu: cortex-a53
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
          base_image: dietpi:rpi_armv8_bullseye

    steps:
    - uses: actions/checkout@v3

    - name: uname
      shell: bash
      run: |
         cat /etc/issue
         uname -a
         autoconf --version
         make -v
         gcc -v
         dpkg -l libpam0g-dev


    - name: autogen
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: ./autogen.sh

    - name: configure
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: ./configure CFLAGS="-Wall -DDEBUG"

    - name: make
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: make

    - name: test
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: |
        ./screen -v
        ./screen --help
